"""
Concrete user feature definitions using FeatureDefinition schemas.
"""

from ...core.schemas import (
    FeatureComputationType,
    FeatureDefinition,
    FeatureGroup,
    FeatureGroupVersion,
    FeatureType,
    ValidationRule,
)

USER_FEATURE_DEFINITIONS = [
    FeatureDefinition(
        name="transaction_count_24h",
        feature_type=FeatureType.INTEGER,
        computation_type=FeatureComputationType.REALTIME,
        description="Number of transactions in the last 24 hours",
        owner="data-team",
        tags=["user", "transaction", "realtime", "fraud"],
        ttl_seconds=86400,
        validation_rules=ValidationRule(min_value=0, max_value=100_000),
    ),
    FeatureDefinition(
        name="avg_transaction_amount_7d",
        feature_type=FeatureType.FLOAT,
        computation_type=FeatureComputationType.BATCH,
        description="Average transaction amount over the last 7 days",
        owner="data-team",
        tags=["user", "transaction", "batch"],
        ttl_seconds=86400,
        validation_rules=ValidationRule(min_value=0.0),
    ),
    FeatureDefinition(
        name="std_transaction_amount_7d",
        feature_type=FeatureType.FLOAT,
        computation_type=FeatureComputationType.BATCH,
        description="Std deviation of transaction amounts over 7 days",
        owner="data-team",
        tags=["user", "transaction", "batch"],
        ttl_seconds=86400,
        validation_rules=ValidationRule(min_value=0.0),
    ),
    FeatureDefinition(
        name="transaction_velocity_1h",
        feature_type=FeatureType.FLOAT,
        computation_type=FeatureComputationType.REALTIME,
        description="Transactions per minute in the last 60 minutes (sliding window)",
        owner="data-team",
        tags=["user", "transaction", "realtime", "fraud"],
        ttl_seconds=3600,
        validation_rules=ValidationRule(min_value=0.0),
    ),
    FeatureDefinition(
        name="unique_merchants_30d",
        feature_type=FeatureType.INTEGER,
        computation_type=FeatureComputationType.BATCH,
        description="Count of unique merchants transacted at in 30 days",
        owner="data-team",
        tags=["user", "merchant", "batch"],
        ttl_seconds=86400,
        validation_rules=ValidationRule(min_value=0),
    ),
    FeatureDefinition(
        name="user_lifetime_value",
        feature_type=FeatureType.FLOAT,
        computation_type=FeatureComputationType.BATCH,
        description="Total transaction value generated by the user (LTV)",
        owner="data-team",
        tags=["user", "ltv", "batch"],
        ttl_seconds=604800,  # 7 days
        validation_rules=ValidationRule(min_value=0.0),
    ),
    FeatureDefinition(
        name="last_login_timestamp",
        feature_type=FeatureType.STRING,
        computation_type=FeatureComputationType.REALTIME,
        description="ISO-8601 timestamp of last login event",
        owner="identity-team",
        tags=["user", "login", "realtime"],
        ttl_seconds=86400,
    ),
    FeatureDefinition(
        name="account_age_days",
        feature_type=FeatureType.INTEGER,
        computation_type=FeatureComputationType.BATCH,
        description="Number of days since account creation",
        owner="identity-team",
        tags=["user", "account"],
        ttl_seconds=86400,
        validation_rules=ValidationRule(min_value=0),
    ),
    FeatureDefinition(
        name="kyc_verified",
        feature_type=FeatureType.BOOLEAN,
        computation_type=FeatureComputationType.REALTIME,
        description="Whether KYC verification has been completed",
        owner="identity-team",
        tags=["user", "compliance"],
    ),
    FeatureDefinition(
        name="typical_active_hours",
        feature_type=FeatureType.LIST,
        computation_type=FeatureComputationType.BATCH,
        description="List of hours (0-23) during which user typically transacts",
        owner="data-team",
        tags=["user", "temporal", "fraud"],
        ttl_seconds=604800,
    ),
]

# Pre-built FeatureGroup with v1
USER_FEATURE_GROUP = FeatureGroup(
    name="user_features",
    entity_type="user",
    description="Real-time and batch features describing user behaviour",
    owner="data-team",
    tags=["user"],
    versions={
        "v1": FeatureGroupVersion(
            version="v1",
            features=USER_FEATURE_DEFINITIONS,
        )
    },
    latest_version="v1",
)
